angular.module("mamarApp").controller("surveyController", [
  "$scope",
  "$timeout",
  function ($scope, $timeout) {
    $scope.displays = [
      {
        name: "form",
        title: "Form",
      },
      {
        name: "wizard",
        title: "Wizard",
      },
    ];
    $scope.form = {
      components: [
        {
          label: "Survey Name",
          labelPosition: "top",
          placeholder: "",
          description: "",
          tooltip: "",
          prefix: "",
          suffix: "",
          widget: {
            type: "input",
          },
          inputMask: "",
          allowMultipleMasks: false,
          customClass: "",
          tabindex: "",
          hidden: false,
          hideLabel: false,
          showWordCount: false,
          showCharCount: false,
          mask: false,
          autofocus: false,
          spellcheck: true,
          disabled: false,
          tableView: true,
          modalEdit: false,
          multiple: false,
          defaultValue: "",
          persistent: true,
          inputFormat: "plain",
          protected: false,
          dbIndex: false,
          case: "",
          encrypted: false,
          redrawOn: "",
          clearOnHide: true,
          customDefaultValue: "",
          calculateValue: "",
          calculateServer: false,
          allowCalculateOverride: false,
          validateOn: "change",
          validate: {
            required: true,
            pattern: "",
            customMessage: "",
            custom: "",
            customPrivate: false,
            json: "",
            minLength: "",
            maxLength: "",
            strictDateValidation: false,
            multiple: false,
            unique: false,
          },
          unique: false,
          errorLabel: "",
          key: "SurveyName",
          tags: [],
          properties: {},
          conditional: {
            show: null,
            when: null,
            eq: "",
            json: "",
          },
          customConditional: "",
          logic: [],
          attributes: {},
          overlay: {
            style: "",
            page: "",
            left: "",
            top: "",
            width: "",
            height: "",
          },
          type: "textfield",
          input: true,
          refreshOn: "",
          inputType: "text",
          id: "eo5042j",
        },
        {
          label: "Submitted By",
          labelPosition: "top",
          placeholder: "",
          description: "",
          tooltip: "",
          prefix: "",
          suffix: "",
          widget: {
            type: "input",
          },
          inputMask: "",
          allowMultipleMasks: false,
          customClass: "",
          tabindex: "",
          hidden: false,
          hideLabel: false,
          showWordCount: false,
          showCharCount: false,
          mask: false,
          autofocus: false,
          spellcheck: true,
          disabled: false,
          tableView: true,
          modalEdit: false,
          multiple: false,
          defaultValue: "",
          persistent: true,
          inputFormat: "plain",
          protected: false,
          dbIndex: false,
          case: "",
          encrypted: false,
          redrawOn: "",
          clearOnHide: true,
          customDefaultValue: "",
          calculateValue: "",
          calculateServer: false,
          allowCalculateOverride: false,
          validateOn: "change",
          validate: {
            required: true,
            pattern: "",
            customMessage: "",
            custom: "",
            customPrivate: false,
            json: "",
            minLength: "",
            maxLength: "",
            strictDateValidation: false,
            multiple: false,
            unique: false,
          },
          unique: false,
          errorLabel: "",
          key: "submittedBy",
          tags: [],
          properties: {},
          conditional: {
            show: null,
            when: null,
            eq: "",
            json: "",
          },
          customConditional: "",
          logic: [],
          attributes: {},
          overlay: {
            style: "",
            page: "",
            left: "",
            top: "",
            width: "",
            height: "",
          },
          type: "textfield",
          input: true,
          refreshOn: "",
          inputType: "text",
          id: "e9iean",
        },
        {
          label: "Submitted Date",
          labelPosition: "top",
          displayInTimezone: "viewer",
          useLocaleSettings: false,
          allowInput: true,
          format: "yyyy-MM-dd hh:mm a",
          placeholder: "",
          description: "",
          tooltip: "",
          customClass: "",
          tabindex: "",
          hidden: false,
          hideLabel: false,
          autofocus: false,
          disabled: false,
          tableView: false,
          modalEdit: false,
          enableDate: true,
          enableMinDateInput: false,
          datePicker: {
            minDate: "",
            maxDate: "",
            disable: "",
            disableFunction: "",
            disableWeekends: false,
            disableWeekdays: false,
            showWeeks: true,
            startingDay: 0,
            initDate: "",
            minMode: "day",
            maxMode: "year",
            yearRows: 4,
            yearColumns: 5,
          },
          enableMaxDateInput: false,
          enableTime: true,
          timePicker: {
            showMeridian: true,
            hourStep: 1,
            minuteStep: 1,
            readonlyInput: false,
            mousewheel: true,
            arrowkeys: true,
          },
          multiple: false,
          defaultValue: "",
          defaultDate: "",
          customOptions: {},
          persistent: true,
          protected: false,
          dbIndex: false,
          encrypted: false,
          redrawOn: "",
          clearOnHide: true,
          customDefaultValue: "",
          calculateValue: "",
          calculateServer: false,
          allowCalculateOverride: false,
          validate: {
            required: true,
            customMessage: "",
            custom: "",
            customPrivate: false,
            json: "",
            strictDateValidation: false,
            multiple: false,
            unique: false,
          },
          unique: false,
          validateOn: "change",
          errorLabel: "",
          key: "SubmittedDate",
          tags: [],
          properties: {},
          conditional: {
            show: null,
            when: null,
            eq: "",
            json: "",
          },
          customConditional: "",
          logic: [],
          attributes: {},
          overlay: {
            style: "",
            page: "",
            left: "",
            top: "",
            width: "",
            height: "",
          },
          type: "datetime",
          timezone: "",
          input: true,
          suffix: '<i ref="icon" class="fa fa-calendar" style=""></i>',
          widget: {
            type: "calendar",
            displayInTimezone: "viewer",
            language: "en",
            useLocaleSettings: false,
            allowInput: true,
            mode: "single",
            enableTime: true,
            noCalendar: false,
            format: "yyyy-MM-dd hh:mm a",
            hourIncrement: 1,
            minuteIncrement: 1,
            time_24hr: false,
            minDate: "",
            disabledDates: "",
            disableWeekends: false,
            disableWeekdays: false,
            disableFunction: "",
            maxDate: "",
          },
          prefix: "",
          refreshOn: "",
          showCharCount: false,
          showWordCount: false,
          allowMultipleMasks: false,
          datepickerMode: "day",
          id: "euhmf4t",
        },
        {
          label: "Are you satisfied with mamar services",
          labelPosition: "top",
          optionsLabelPosition: "right",
          description: "",
          tooltip: "",
          customClass: "",
          tabindex: "",
          inline: false,
          hidden: false,
          hideLabel: false,
          autofocus: false,
          disabled: false,
          tableView: false,
          modalEdit: false,
          defaultValue: {
            "": false,
          },
          values: [
            {
              label: "",
              value: "",
            },
          ],
          persistent: true,
          protected: false,
          dbIndex: false,
          encrypted: false,
          redrawOn: "",
          clearOnHide: true,
          customDefaultValue: "",
          calculateValue: "",
          calculateServer: false,
          allowCalculateOverride: false,
          validate: {
            required: true,
            customMessage: "",
            custom: "",
            customPrivate: false,
            json: "",
            strictDateValidation: false,
            multiple: false,
            unique: false,
          },
          errorLabel: "",
          minSelectedCountMessage: "",
          maxSelectedCountMessage: "",
          key: "SurveyQuestion1",
          tags: [],
          properties: {},
          conditional: {
            show: null,
            when: null,
            eq: "",
            json: "",
          },
          customConditional: "",
          logic: [],
          attributes: {},
          overlay: {
            style: "",
            page: "",
            left: "",
            top: "",
            width: "",
            height: "",
          },
          type: "selectboxes",
          input: true,
          placeholder: "",
          prefix: "",
          suffix: "",
          multiple: false,
          unique: false,
          refreshOn: "",
          widget: null,
          validateOn: "change",
          showCharCount: false,
          showWordCount: false,
          allowMultipleMasks: false,
          inputType: "checkbox",
          fieldSet: false,
          id: "e5j11m8",
        },
        {
          type: "button",
          label: "Submit",
          key: "submit",
          size: "md",
          block: false,
          action: "submit",
          disableOnInvalid: true,
          theme: "primary",
          input: true,
          placeholder: "",
          prefix: "",
          customClass: "",
          suffix: "",
          multiple: false,
          defaultValue: null,
          protected: false,
          unique: false,
          persistent: false,
          hidden: false,
          clearOnHide: true,
          refreshOn: "",
          redrawOn: "",
          tableView: false,
          modalEdit: false,
          labelPosition: "top",
          description: "",
          errorLabel: "",
          tooltip: "",
          hideLabel: false,
          tabindex: "",
          disabled: false,
          autofocus: false,
          dbIndex: false,
          customDefaultValue: "",
          calculateValue: "",
          calculateServer: false,
          widget: {
            type: "input",
          },
          attributes: {},
          validateOn: "change",
          validate: {
            required: false,
            custom: "",
            customPrivate: false,
            strictDateValidation: false,
            multiple: false,
            unique: false,
          },
          conditional: {
            show: null,
            when: null,
            eq: "",
          },
          overlay: {
            style: "",
            left: "",
            top: "",
            width: "",
            height: "",
          },
          allowCalculateOverride: false,
          encrypted: false,
          showCharCount: false,
          showWordCount: false,
          properties: {},
          allowMultipleMasks: false,
          leftIcon: "",
          rightIcon: "",
          dataGridLabel: true,
          id: "ei3howg",
        },
      ],
      display: "form",
    };

    $scope.renderForm = true;
    //$scope.$on("formUpdate", function (event, form) {
    //  angular.merge($scope.form, form);
    //  $scope.renderForm = false;
    //  setTimeout(function () {
    //    $scope.renderForm = true;
    //  }, 10);
    //});

    //// var originalComps = _.cloneDeep($scope.form.components);
    //var originalComps = { ...$scope.form.components }
    //$scope.jsonCollapsed = true;
    //$timeout(function () {
    //  $scope.jsonCollapsed = false;
    //}, 200);
    //var currentDisplay = "form";
    //$scope.$watch("form.display", function (display) {
    //  if (display && display !== currentDisplay) {
    //    currentDisplay = display;
    //    if (display === "form") {
    //      $scope.form.components = originalComps;
    //    } else {
    //      $scope.form.components = [
    //        {
    //          type: "panel",
    //          input: false,
    //          title: "Page 1",
    //          theme: "default",
    //          components: originalComps,
    //        },
    //      ];
    //    }
    //  }
    //});
  },
]);
